# Private Cloud SQL PostgreSQL 16.
#
# Two databases on one instance:
#   - twenty       : the pilot application database
#   - twenty_test  : the disposable database boundary for destructive T3 tests (CL2)
#
# The graph requires a disposable boundary for destructive tests. A separate DATABASE on the same
# instance is chosen over a separate instance because it keeps cost flat and still gives CL2 a
# target it can drop and recreate without touching pilot data. Workspace-level isolation inside
# `twenty` is the second boundary; both are used.

resource "google_sql_database_instance" "main" {
  count = local.gate

  name             = "${var.name_prefix}-pg"
  region           = var.region
  database_version = "POSTGRES_16"

  # Terraform-side guard only: blocks `terraform destroy` from removing this instance. It is NOT
  # visible to the GCP API, so it does nothing against a console click or a `gcloud sql instances
  # delete`. Both guards are needed; setting only this one was the original gap, caught by
  # scripts/50-verify-acceptance.sh checking the API-level field.
  deletion_protection = var.sql_deletion_protection

  settings {
    tier              = var.sql_tier
    availability_type = var.sql_availability_type
    disk_type         = "PD_SSD"
    disk_size         = var.sql_disk_gb
    disk_autoresize   = true
    edition           = "ENTERPRISE"

    # API-level guard: what actually stops a console or gcloud deletion. Driven by the same
    # variable as the Terraform-side guard so the teardown runbook's
    # `-var="sql_deletion_protection=false"` correctly disarms both in one step.
    deletion_protection_enabled = var.sql_deletion_protection

    user_labels = local.common_labels

    ip_configuration {
      # No public IP. This is the acceptance criterion "database is not publicly exposed".
      ipv4_enabled                                  = false
      private_network                               = google_compute_network.vpc[0].id
      enable_private_path_for_google_cloud_services = true
      ssl_mode                                      = "ENCRYPTED_ONLY"
    }

    backup_configuration {
      enabled = true
      # MUST be inside the scheduled running window. A stopped Cloud SQL instance takes no
      # automated backup and reports no error — the backup simply never happens. The original
      # 01:00 UTC would have fallen at 04:00 Asia/Riyadh, with the instance stopped.
      start_time                     = var.sql_backup_start_time_utc
      point_in_time_recovery_enabled = true
      transaction_log_retention_days = var.sql_pitr_retention_days
      location                       = var.region

      backup_retention_settings {
        retained_backups = var.sql_backup_retention_days
        retention_unit   = "COUNT"
      }
    }

    maintenance_window {
      day          = 7 # Sunday
      hour         = 2
      update_track = "stable"
    }

    insights_config {
      query_insights_enabled  = true
      query_string_length     = 1024
      record_application_tags = true
      record_client_address   = false # avoids storing client IPs alongside query text
    }

    database_flags {
      name  = "cloudsql.iam_authentication"
      value = "on"
    }

    # Twenty's server plus worker plus the CL2 integration suite open more connections than the
    # small-tier default. Exhausted connections is an explicit rollback trigger in the graph.
    database_flags {
      name  = "max_connections"
      value = "200"
    }

    database_flags {
      name  = "log_min_duration_statement"
      value = "1000" # surfaces the >1s p95 rollback trigger
    }
  }

  depends_on = [
    google_service_networking_connection.psa,
    google_project_service.required,
  ]
}

resource "google_sql_database" "app" {
  count = local.gate

  name     = "twenty"
  instance = google_sql_database_instance.main[0].name
}

resource "google_sql_database" "disposable_test" {
  count = local.gate

  name     = "twenty_test"
  instance = google_sql_database_instance.main[0].name

  # CL2 drops and recreates this. Terraform must not fight it.
  lifecycle {
    ignore_changes = [name]
  }
}

# Password is generated by Terraform and written straight into Secret Manager. It is never
# printed, never committed, and never placed in a tfvars file. It does land in Terraform state,
# which is why state lives in a private, versioned GCS bucket and never in the repository.
resource "random_password" "app_db" {
  count = local.gate

  length           = 32
  special          = true
  override_special = "-_.~"
}

resource "google_sql_user" "app" {
  count = local.gate

  name     = "twenty_app"
  instance = google_sql_database_instance.main[0].name
  password = random_password.app_db[0].result
}
