import { type CSSProperties } from 'react';

const theme = {
  backgroundPrimary: 'var(--t-background-primary)',
  backgroundSecondary: 'var(--t-background-secondary)',
  borderMedium: 'var(--t-border-color-medium)',
  borderLight: 'var(--t-border-color-light)',
  radius: 'var(--t-border-radius-sm)',
  textPrimary: 'var(--t-font-color-primary)',
  textSecondary: 'var(--t-font-color-secondary)',
  textTertiary: 'var(--t-font-color-tertiary)',
  textInverted: 'var(--t-font-color-inverted)',
  fontFamily: 'var(--t-font-family)',
  fontXs: 'var(--t-font-size-xs)',
  fontSm: 'var(--t-font-size-sm)',
  fontMd: 'var(--t-font-size-md)',
  weightMedium: 'var(--t-font-weight-medium)',
  weightSemibold: 'var(--t-font-weight-semi-bold)',
  actionPrimary: 'var(--t-color-blue)',
  actionDisabled: 'var(--t-accent-accent4060)',
};

export const createVendorPurchaseOrderStyles: Record<string, CSSProperties> = {
  container: {
    background: theme.backgroundPrimary,
    color: theme.textPrimary,
    display: 'flex',
    flexDirection: 'column',
    fontFamily: theme.fontFamily,
    fontSize: theme.fontSm,
    height: '100%',
  },
  header: {
    borderBottom: `1px solid ${theme.borderLight}`,
    padding: '16px',
  },
  title: {
    fontSize: theme.fontMd,
    fontWeight: theme.weightSemibold,
    margin: 0,
  },
  subtitle: {
    color: theme.textTertiary,
    lineHeight: 1.5,
    margin: '8px 0 0',
  },
  body: {
    display: 'flex',
    flex: 1,
    flexDirection: 'column',
    gap: '16px',
    overflowY: 'auto',
    padding: '16px',
  },
  field: { display: 'flex', flexDirection: 'column', gap: '8px' },
  label: {
    color: theme.textSecondary,
    fontSize: theme.fontXs,
    fontWeight: theme.weightMedium,
  },
  input: {
    background: theme.backgroundSecondary,
    border: `1px solid ${theme.borderMedium}`,
    borderRadius: theme.radius,
    boxSizing: 'border-box',
    color: theme.textPrimary,
    fontFamily: theme.fontFamily,
    fontSize: theme.fontSm,
    minHeight: '44px',
    padding: '10px 12px',
    width: '100%',
  },
  helper: { color: theme.textTertiary, fontSize: theme.fontXs },
  footer: {
    borderTop: `1px solid ${theme.borderLight}`,
    display: 'flex',
    gap: '8px',
    justifyContent: 'flex-end',
    padding: '12px 16px',
  },
  button: {
    border: '1px solid transparent',
    borderRadius: theme.radius,
    cursor: 'pointer',
    fontFamily: theme.fontFamily,
    fontSize: theme.fontSm,
    fontWeight: theme.weightMedium,
    minHeight: '44px',
    padding: '0 16px',
  },
  secondaryButton: {
    background: theme.backgroundSecondary,
    borderColor: theme.borderMedium,
    color: theme.textSecondary,
  },
  primaryButton: {
    background: theme.actionPrimary,
    color: theme.textInverted,
  },
  disabledButton: {
    background: theme.actionDisabled,
    cursor: 'not-allowed',
  },
};
